"""empty message

Revision ID: b88a0a83caf6
Revises: 5f15fc302bf0
Create Date: 2019-10-17 16:41:14.992988

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b88a0a83caf6'
down_revision = '5f15fc302bf0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('article', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'article', 'user', ['author_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'article', type_='foreignkey')
    op.drop_column('article', 'author_id')
    # ### end Alembic commands ###
